name: Publish Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.1
    - name: Set up JDK 17
      uses: actions/setup-java@v4.4.0
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Gradle Wrapper Validation
      # You may pin to the exact commit or the version.
      uses: gradle/actions/wrapper-validation@v4.1.0
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4.1.0
    - name: Build with Gradle
      run: ./gradlew shadowjar
    - name: Get App Version
      id: get_version
      run: echo "version=$(./gradlew getVersion --console=plain -q --warning-mode=none)" >> $GITHUB_ENV
    - uses: actions/upload-artifact@v4.4.3
      with:
        name: Package
        path: |
          ./build/libs/VOTL-*
        overwrite: true
    - name: Create Release
      # You may pin to the exact commit or the version.
      uses: ncipollo/release-action@v1.14.0
      with:
        allowUpdates: true
        # An optional set of paths representing artifacts to upload to the release. This may be a single path or a comma delimited list of paths (or globs)
        artifacts: ./build/libs/VOTL-*.jar
        artifactContentType: "raw"
        # Generate release notes. There needs to be a previous version for it to diff against.
        generateReleaseNotes: true
        # Optionally marks this release as prerelease. Set to true to enable.
        prerelease: (contains( ${{ env.version }} , 'SNAPSHOT'))
        # Indicates if existing release artifacts should be replaced. Defaults to true.
        replacesArtifacts: true
        # An optional tag for the release. If this is omitted the git ref will be used (if it is a tag).
        tag: ${{ env.version }}
        # The Github token.
        token: ${{ secrets.TOKEN }}
